import React from "react";
import getProducts from "../lib/getProducts";
import Head from "next/head";
import PaginationPage from "../components/PaginatedPage/PaginatedPage";
import styles from "@/styles/Home.module.css";
export const PER_PAGE = 10;

function PaginatedPage({ products, currentPage, totalProducts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <PaginationPage
            products={products}
            currentPage={currentPage}
            totalProducts={totalProducts}
            perPage={PER_PAGE}
          />
        </div>
      </main>
    </>
  );
}

export const getStaticProps = async ({ params }) => {
  const page = Number(params?.page) || 1;
  const { products, total } = await getProducts({ limit: PER_PAGE, page });

  if (!products.length) {
    return {
      notFound: true,
    };
  }

  if (page === 1) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {
      products,
      totalProducts: total,
      currentPage: page,
    },
    revalidate: 60 * 60 * 24, // <--- ISR cache: once a day
  };
};

export const getStaticPaths = async () => {
  return {
    paths: Array.from({ length: 5 }).map((_, i) => `/${i + 2}`),
    fallback: "blocking",
  };
};

export default PaginatedPage;
