import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import getProducts from "../lib/getProducts";
import { PER_PAGE } from "./[page]";
import PaginationPage from "../components/PaginatedPage/PaginatedPage";

export default function Home({ products, totalProducts, currentPage }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <PaginationPage
            products={products}
            currentPage={currentPage}
            totalProducts={totalProducts}
            perPage={PER_PAGE}
          />
        </div>
      </main>
    </>
  );
}
export const getStaticProps = async () => {
  const { products, total } = await getProducts({ limit: PER_PAGE, page: 1 });

  return {
    props: {
      products,
      totalProducts: total,
      currentPage: 1,
    },
  };
};
